### ISSUE TITLE
command `lxc file pull alpine/usr/bin/lxc /tmp/lxc` fails on Alpine

### ISSUE THREAD

**Issue by KSPAtlas** [edeloya/ChromeOS-Terminal-LXC-LXD#1]
Yes, I am sure that the container is named alpine. However, on an alpine/3.15 container, the command simply fails with `Error: not found`. The -v flag does nothing.

**Comment by edeloya** [comment]
Im pretty sure its because a fresh install of alpine wont have lxc there.

You dont have to use ubuntu:18.04, we only pull in that image to take lxc from its `/usr/bin/` folder. You can delete that container once you move lxc into the `penguin` container.

I don't know why they stopped including lxc in ubuntu past 18.04, so thats why we get specifically that version. I mostly did it this way because I looked at lxc's _Getting Started_ page and decided that was more work and I just wanted to get this working.

**Comment by KSPAtlas** [comment]
Just make that more explicit in the tutorial.

**Comment by KSPAtlas** [comment]
Nevermind, still doesn't work with Ubuntu 18.04

**Comment by KSPAtlas** [comment]
nvm i did a command wrong

**Comment by edeloya** [comment]
> nvm i did a command wrong

Damn is just finished recording this from fresh install lol

https://user-images.githubusercontent.com/54195989/143625358-77cf631b-10c2-4c08-92e9-5771d5a624c9.mp4
